[package]
name = "telepair-agent"
version = "0.1.2"
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
telepair-core = { workspace = true }
portable-pty = { workspace = true }
bytes = { workspace = true }
serde = { workspace = true }
serde_yaml = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
futures = { workspace = true }
